### ISSUE TITLE
You should implement .With handler's methods

### ISSUE THREAD

**Issue by lictw** [cyrusaf/ctxlog#3]
Now .With and .WithGroup cannot be used cause default handler return.

**Comment by sgielen** [comment]
@cyrusaf can confirm that this makes the package break if `.With()` is used.

Here's an example:

```
package main

import (
	"context"
	"log/slog"
	"os"

	"github.com/cyrusaf/ctxlog"
)

func main() {
	var handler slog.Handler
	handler = slog.NewJSONHandler(os.Stdout, nil)

	// ctxlog takes slog.Attrs from the context and adds them to records.
	handler = ctxlog.NewHandler(handler)

	// Any attrs we add here, will occur in *all* records.
	logger := slog.New(handler)
	//logger = logger.With(slog.String("process", "main"))

	ctx := ctxlog.WithAttrs(context.Background(), slog.String("this", "is a test"))
	logger.InfoContext(ctx, "here we are")
}
```

This code logs a single INFO message with `msg` and `this` attr. But, when the `logger.With()` line is uncommented, while the attr `process` is added, the attr `this` is lost.

**Comment by sgielen** [comment]
#4 fixes this and amends the tests.

**Comment by cyrusaf** [comment]
Hi @sgielen and @lictw, sorry for the delay. I spent some writing up a solution to this that looked similar to #4 a few weeks ago and realized some strange behavior with the `WithGroup` function. Because this package logs the attributes set on the context at log time, using `WithGroup` will lead to all the attributes being nested under the group. To me, this doesn't seem like the ideal behavior, but I'm open to discussing further. Here is an example from my tests:

```golang
ctx = ctxlog.WithAttrs(ctx, slog.String("hello", "world"))
groupLogger := logger.WithGroup("group")
slog.SetDefault(groupLogger)
slog.InfoContext(ctx, "test")
```

```json
{
  "level": "INFO",
  "msg": "test",
  "group": {
    "hello": "world"
  }
}
```

Given the order of commands I would probably expect the log to look like:
```json
{
  "level": "INFO",
  "msg": "test",
  "hello": "world",
  "group": {}
}
```

What are your thoughts on expected behavior here? I'll write up some thoughts on a potential solution in another commet.

**Comment by cyrusaf** [comment]
As a potential solution, I was thinking instead of attaching the attributes to the context, we could attach a logger instead and then grab that logger at log time. Not sure if this has any performance implications. For example we could change `WithAttrs `to the following:
```golang
func WithAttrs(ctx context.Context, attrs ...slog.Attr) context.Context {
	// Get logger if set
	logger, _ := ctx.Value(loggerKey).(*slog.Logger)
	logger = logger.With(attrs...)
	ctx = context.WithValue(ctx, loggerKey, logger)
	return ctx
}
```

The ctxlog handler could then fetch the logger from the context rather than fetching attributes from the ctx and attaching them to the default logger. Thoughts?

**Comment by sgielen** [comment]
Right -- I never use `WithGroup` so I never realized this issue, but I see your point.

I am using this package precisely because I didn't want to put the logger in the ctx. See the "Controversy" paragraph of https://github.com/golang/go/issues/58243. I agreed with some of the points made there, so I tried to go for a solution where my ctx contains contextual information for use by logging but not the logger itself - and ctxlog provided this. Having the package based on adding a logger to ctx defeats that purpose for me. I am not entirely against it conceptually, but if the package goes that route, I wonder why we even have ctxlog, and not the tiny wrapper suggested by https://github.com/golang/go/issues/58243.

I don't have a solution for `WithGroup` OTOH. I have never used it, so I'm not sure what its use-cases are. I wonder whether we could do something like

```
type Handler struct {
  slog.Handler
  Group string
}

func (t Handler) WithAttrs(attrs []slog.Attr) slog.Handler {
	h := t.Handler
	if t.Group != "" {
		h = h.WithGroup(t.Group)
	}
	h = h.WithAttrs(attrs)
	return Handler{h, Group: t.Group}
}

func (t Handler) WithGroup(name string) slog.Handler {
	return Handler{t.Handler, Group: name}
}
```

As I said I'm not sure if this completely captures the intention of WithGroup?

Edit: I see a similar method used here: https://github.com/golang/go/issues/58243#issuecomment-1702537952

**Comment by cyrusaf** [comment]
I don't want to block getting the `.WithAttrs` fix in and don't think `.WithGroup` will be very commonly used with this handler. So let's merge your solution for now and I will open a new issue to track the `.WithGroup` issue and solution.

**Comment by cyrusaf** [comment]
Created a new tag and release with this fix: https://github.com/cyrusaf/ctxlog/releases/tag/v1.2.0. Thanks @sgielen and @lictw!

**Comment by sgielen** [comment]
Thank you @cyrusaf!
